name       : perl-alien-libxml2
version    : 0.19
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Libxml2-0.19.tar.gz : f4a674099bbd5747c0c3b75ead841f3b244935d9ef42ba35368024bd611174c9
homepage   : https://metacpan.org/dist/Alien-Libxml2
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Install the C libxml2 library on your system 
description: |
    Install the C libxml2 library on your system
builddeps  :
    - perl-alien-build-plugin-download-gitlab
    - perl-capture-tiny
    - perl-file-chdir
    - perl-file-which
    - perl-uri
rundeps    :
    - perl-alien-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
